device: "cuda:0"
logs_root: "logs"
image_url_template: "https://en.pimg.jp/{:03d}/{:03d}/{:03d}/1/{}.jpg"
data_dir: "data/pixta-390k"
model_files:
  # ViT-B/32: "openai-ViT-B-32"
#   ViT-B-32-laion2B: "laion/CLIP-ViT-B-32-laion2B-s34B-b79K"
#   ViT-H-14-laion2B: "laion/CLIP-VeiT-H-14-laion2B-s32B-b79K"
  # DFN-5B: "apple/DFN5B-CLIP-ViT-H-14-378"